### ISSUE TITLE
Please consider tagging releases

### ISSUE THREAD

**Issue by scgilardi** [keechma/keechma-toolbox#11]
- I have the keechma-toolbox docs loaded into [Dash](https://kapeli.com/dash) and it notified me of the new release.
- I came here looking to see what changed and I found out by looking through the commits.
- With other projects, I've found it convenient to be able to find the code for _any_ release by selecting the associated tag (e.g., `v1.2.5` or `1.2.5`) from Github's "Branch/Tags" UI on the repo's main page.
- Please consider tagging new releases upon release for the suite of repos under Keechma using an [annotated tag](https://dev.to/neshaz/a-tutorial-for-tagging-releases-in-git-147e).

**Comment by retro** [comment]
Tag for 0.1.25 is added and will be added for future versions
