### ISSUE TITLE
Forms on-change helper for CJK text

### ISSUE THREAD

**Issue by sooheon** [keechma/keechma-toolbox#2]
Problem: keechma forms does not play nice with CJK input methods, where several keypresses glom into a single character. In Korean, for example, the sequence `ㅇㅏㄴㄴㅕㅇ`  results in `안녕` printed on the screen.

In the realworld [example](https://gothinkster.github.io/clojurescript-keechma-realworld-example-app/#!editor) which uses keechma toolbox forms helpers, the characters are joined incorrectly.

## Expected result:
Keypresses:  `ㅇㅏㄴㄴㅕㅇㅎㅏㅅㅔㅇㅛ` => `안녕하세요`

## Actual result:
Here is the result of me typing the same text ("안녕하세요") several times:

<img width="1064" alt="screen shot 2018-01-21 at 5 33 51 am" src="https://user-images.githubusercontent.com/302945/35187778-b377d730-fe6c-11e7-9c91-5be392dbaff1.png">
 

- Related issue in React: https://github.com/facebook/react/issues/3926
- [demo](https://eyesofkids.github.io) of desired behavior, and relevant React [code](https://github.com/eyesofkids/react-compositionevent)

**Comment by retro** [comment]
@sooheon Please close this issue if this fixes it for you https://github.com/gothinkster/clojurescript-keechma-realworld-example-app/commit/2667f05d26de4c9d67f144aa0418a23c8381ef62
