### ISSUE TITLE
Errors in dataloader silently caught

### ISSUE THREAD

**Issue by mjmeintjes** [keechma/keechma-toolbox#7]
I just had this where I had an error inside one of the my loader functions, but I just couldn't figure out what was going on.

Finally (after some digging), I found the following little line:
https://github.com/keechma/keechma-toolbox/blob/459500b514247b95348d41bcd1bd66a6d20add2f/src/cljs/keechma/toolbox/dataloader/controller.cljs#L51

What this does is swallow any errors that happen inside loader functions. Not sure why it is needed, but if it is needed, it would be useful to add some type of logging to it.

**Comment by retro** [comment]
@mjmeintjes You're right. This is needed because sometimes old dataloader promise will be rejected if the new instance is started before the old one is resolved. I think that the solution would be to ignore only this kind of error and bubble the other ones.

**Comment by retro** [comment]
@mjmeintjes can you checkout the latest to check if it works correctly for you? I'm planning to do a release soon

**Comment by retro** [comment]
@mjmeintjes I've released a new version - `0.1.14` which addresses this problem. It will report datasource errors in develop / debug mode
