### ISSUE TITLE
Pipeline controller with websocket or setInterval

### ISSUE THREAD

**Issue by endenwer** [keechma/keechma-toolbox#8]
I want to use websocket and setInterval in pipeline controller. With regular controller I can just init websocket in `start` function and remove it in `stop` function. Can I do it in pipeline controller?

**Comment by retro** [comment]
@endenwer Not directly, but you have a few options:

1. Use a normal controller and just re-send or broadcast commands that come from the websockets
2. Use a normal controller and call pipelines from the handler function

If you want to go with the second option, this is how the code could look:

```clojure
(def pipelines
  :foo-bar (pipeline! [value app-db]
             (do-something-in-pipeline)))

(defmethod controller/handler MyController [this app-db-atom in-chan _]
  (go-loop []
    (let [[command args] (<! in-chan)]
      (case command
        :websocket (do-something-with-websocket args)
        :set-interval (do-something-with-set-interval args)
        (when-let [pipeline (get pipelines command)]
          (pipeline this app-db-atom args)))
      (when command (recur)))))
```

**Comment by endenwer** [comment]
@retro Thanks. I used first option before, but second looks better.
